config/routes.rb
Rails.application.routes.draw do
  resources :shop_views
  resources :brands do
    resources :products do
      resources :shops
    end
  end
  resources :posts
  
  get 'home/index'
  get 'home/sosanh'
  get 'admin/index'

  root 'home#index'

  get 'static_pages/help'

end

app/models/shop.rb
class Shop
  include Mongoid::Document
  include Mongoid::Timestamps
  field :shop_name, type: String
  field :shop_image, type: String
  field :shop_description, type: String

  embedded_in :product, inverse_of: :shops
end

app/models/shop_view.rb
class ShopView
  include Mongoid::Document
  include Mongoid::Timestamps
  field :shop_view_name, type: String
  field :shop_view_image, type: String
  field :shop_view_description, type: String
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :load_product
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = @product.shops
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = @product.shops.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = @product.shops.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to [@brand, @product, @shop], notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to [@brand, @product, @shop], notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to brand_product_shops_url(@brand, @product), notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = @product.shops.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:shop_name, :shop_image, :shop_description)
    end

    def load_product
      @brand = Brand.find(params[:brand_id])
      @product = @brand.products.find(params[:product_id])
    end

    def load_shop_view
      
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for([@brand, @product, @shop]) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop_name %><br>
    <%= f.text_field :shop_name %>
  </div>
  <div class="field">
    <%= f.label :shop_image %><br>
    <%= f.text_field :shop_image %>
  </div>
  <div class="field">
    <%= f.label :shop_description %><br>
    <%= f.text_field :shop_description %>
  </div>
  <div class="field">
    <%= f.select  :id,  ShopView.all.map{ |c| [c.shop_view_name, c.id,{'data-shop_view_image': c.shop_view_image,'data-shop_view_name': c.shop_view_name}]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', brand_product_shop_path(@brand, @product, @shop) %> |
<%= link_to 'Back', brand_product_shops_path(@brand, @product) %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shops</h1>

<table>
  <thead>
    <tr>
      <th>Shop name</th>
      <th>Shop image</th>
      <th>Shop description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.shop_name %></td>
        <td><%= shop.shop_image %></td>
        <td><%= shop.shop_description %></td>
        <td><%= link_to 'Show', brand_product_shop_path(@brand, @product, shop) %></td>
        <td><%= link_to 'Edit', edit_brand_product_shop_path(@brand, @product,shop) %></td>
        <td><%= link_to 'Destroy', [@brand, @product, shop], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_brand_product_shop_path(@brand, @product) %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', brand_product_shops_path(@brand, @product) %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop name:</strong>
  <%= @shop.shop_name %>
</p>

<p>
  <strong>Shop image:</strong>
  <%= @shop.shop_image %>
</p>

<p>
  <strong>Shop description:</strong>
  <%= @shop.shop_description %>
</p>

<%= link_to 'Edit', edit_brand_product_shop_path(@brand, @product, @shop) %> |
<%= link_to 'Back', brand_product_shops_path(@brand, @product, @shop) %>