config/routes.rb
Rails.application.routes.draw do
  resources :shop_views
  resources :brands do
    resources :products do
      resources :shops
    end
  end
  resources :posts
  
  get 'home/index'
  get 'home/sosanh'
  get 'admin/index'

  root 'home#index'

  get 'static_pages/help'

end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  field :product_name, type: String
  field :product_image, type: String
  field :product_description, type: String

  embedded_in :brand, inverse_of: :products
  embeds_many :shops
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_brand
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = @brand.products.last(2).reverse
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = @brand.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = @brand.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@brand , @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [@brand, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to brand_products_url(@brand), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = @brand.products.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :product_image, :product_description, :shops)
    end

    def load_brand
      @brand = Brand.find(params[:brand_id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@brand, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_image %><br>
    <%= f.text_field :product_image %>
  </div>
  <div class="field">
    <%= f.label :product_description %><br>
    <%= f.text_field :product_description %>
  </div>
  <div class="field">
    <%= f.label :shop %><br>
      <%= f.select  :shops, Shop.all.map{|e| [e.shop_name,e.id] } %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', brand_product_path(@brand, @product) %> |
<%= link_to 'Back', brand_products_path(@brand) %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product image</th>
      <th>Product description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.product_image %></td>
        <td><%= product.product_description %></td>
        <td><%= link_to 'Show', brand_product_path(@brand, product) %></td>
        <td><%= link_to 'Edit', edit_brand_product_path(@brand, product) %></td>
        <td><%= link_to 'Destroy', [@brand , product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_brand_product_path(@brand) %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', brand_products_path(@brand) %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product image:</strong>
  <%= @product.product_image %>
</p>

<p>
  <strong>Product description:</strong>
  <%= @product.product_description %>
</p>

<%= link_to 'Edit', edit_brand_product_path(@brand , @product) %> |
<%= link_to 'Back', brand_products_path(@brand) %>