config/routes.rb
Rails.application.routes.draw do
  resources :shop_views
  resources :brands do
    resources :products do
      resources :shops
    end
  end
  resources :posts
  
  get 'home/index'
  get 'home/sosanh'
  get 'admin/index'

  root 'home#index'

  get 'static_pages/help'

end

app/controllers/shop_views_controller.rb
class ShopViewsController < ApplicationController
  before_action :set_shop_view, only: [:show, :edit, :update, :destroy]

  # GET /shop_views
  # GET /shop_views.json
  def index
    @shop_views = ShopView.all
  end

  # GET /shop_views/1
  # GET /shop_views/1.json
  def show
  end

  # GET /shop_views/new
  def new
    @shop_view = ShopView.new
  end

  # GET /shop_views/1/edit
  def edit
  end

  # POST /shop_views
  # POST /shop_views.json
  def create
    @shop_view = ShopView.new(shop_view_params)

    respond_to do |format|
      if @shop_view.save
        format.html { redirect_to @shop_view, notice: 'Shop view was successfully created.' }
        format.json { render :show, status: :created, location: @shop_view }
      else
        format.html { render :new }
        format.json { render json: @shop_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_views/1
  # PATCH/PUT /shop_views/1.json
  def update
    respond_to do |format|
      if @shop_view.update(shop_view_params)
        format.html { redirect_to @shop_view, notice: 'Shop view was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_view }
      else
        format.html { render :edit }
        format.json { render json: @shop_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_views/1
  # DELETE /shop_views/1.json
  def destroy
    @shop_view.destroy
    respond_to do |format|
      format.html { redirect_to shop_views_url, notice: 'Shop view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_view
      @shop_view = ShopView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_view_params
      params.require(:shop_view).permit(:shop_view_name, :shop_view_image, :shop_view_description)
    end
end

app/helpers/shop_views_helper.rb
module ShopViewsHelper
end

app/views/shop_views/_form.html.erb
<%= form_for(@shop_view) do |f| %>
  <% if @shop_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_view.errors.count, "error") %> prohibited this shop_view from being saved:</h2>

      <ul>
      <% @shop_view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop_view_name %><br>
    <%= f.text_field :shop_view_name %>
  </div>
  <div class="field">
    <%= f.label :shop_view_image %><br>
    <%= f.text_field :shop_view_image %>
  </div>
  <div class="field">
    <%= f.label :shop_view_description %><br>
    <%= f.text_field :shop_view_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_views/edit.html.erb
<h1>Editing Shop View</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_view %> |
<%= link_to 'Back', shop_views_path %>

app/views/shop_views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shop Views</h1>

<table>
  <thead>
    <tr>
      <th>Shop view name</th>
      <th>Shop view image</th>
      <th>Shop view description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_views.each do |shop_view| %>
      <tr>
        <td><%= shop_view.shop_view_name %></td>
        <td><%= shop_view.shop_view_image %></td>
        <td><%= shop_view.shop_view_description %></td>
        <td><%= link_to 'Show', shop_view %></td>
        <td><%= link_to 'Edit', edit_shop_view_path(shop_view) %></td>
        <td><%= link_to 'Destroy', shop_view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop view', new_shop_view_path %>

app/views/shop_views/new.html.erb
<h1>New Shop View</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_views_path %>

app/views/shop_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop view name:</strong>
  <%= @shop_view.shop_view_name %>
</p>

<p>
  <strong>Shop view image:</strong>
  <%= @shop_view.shop_view_image %>
</p>

<p>
  <strong>Shop view description:</strong>
  <%= @shop_view.shop_view_description %>
</p>

<%= link_to 'Edit', edit_shop_view_path(@shop_view) %> |
<%= link_to 'Back', shop_views_path %>